version: '3.2'
services:
  redis:
    image: redis:alpine3.14
    restart: always
    ports:
        - 6379:6379
    command: redis-server --requirepass test_pass
    volumes:
      - redis_data:/data
volumes:
  redis_data: